### ISSUE TITLE
Issue with register.py file and Inquiry Regarding Code Adjustment

### ISSUE THREAD

**Issue by CYXYZ** [eigenvivek/DiffPose#16]
Dear Vivek,

I hope this email finds you well. I am writing to address an issue I encountered while working with the register.py file in both the main and refactor-se3 branches of our project.

Specifically, I noticed that when I attempt to input the parameterization "euler_angles," an error occurs, as follows:

```
Traceback (most recent call last):
  File "/home/data/cyx/autodl-tmp/DiffPose-main/experiments/deepfluoro/register.py", line 381, in <module>
    main(id_number, parameterization=parameterization)
  File "/home/data/cyx/autodl-tmp/DiffPose-main/experiments/deepfluoro/register.py", line 348, in main
    df = registration.run(idx)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/autodl-tmp/DiffPose-main/experiments/deepfluoro/register.py", line 189, in run
    registration = self.initialize_registration(img)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/autodl-tmp/DiffPose-main/experiments/deepfluoro/register.py", line 124, in initialize_registration
    return SparseRegistration(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/preop/lib/python3.11/site-packages/diffpose/registration.py", line 99, in __init__
    rotation, translation = convert(
                            ^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/preop/lib/python3.11/site-packages/diffpose/calibration.py", line 119, in convert
    transform.get_rotation(output_parameterization, output_convention),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/preop/lib/python3.11/site-packages/diffpose/calibration.py", line 52, in get_rotation
    R = convert_so3(R, "matrix", parameterization, None, convention)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/preop/lib/python3.11/site-packages/diffdrr/utils.py", line 91, in convert
    return _convert_from_rotation_matrix(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/preop/lib/python3.11/site-packages/diffdrr/utils.py", line 126, in _convert_from_rotation_matrix
    rotation = matrix_to_euler_angles(matrix, convention)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/preop/lib/python3.11/site-packages/diffdrr/utils.py", line 419, in matrix_to_euler_angles
    if len(convention) != 3:
       ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

```

This issue seems to persist regardless of the branch I am working in(main and refactor-se3). Upon further investigation, I realized that the code snippet provided below is likely the cause of the error:

```
id_numbers = [1, 2, 3, 4, 5, 6]
parameterizations = [
    "se3_log_map",
    "so3_log_map",
    "axis_angle",
    "euler_angles",
    "quaternion",
    "rotation_6d",
    "rotation_10d",
    "quaternion_adjugate",
]
id_numbers = [i for i, _ in product(id_numbers, parameterizations)]
parameterizations = [p for _, p in product(id_numbers, parameterizations)]
```

Moreover, I am considering using alternative parameterizations in the **train.py** file. Would it be necessary to modify the function signature in train.py, particularly the parameterization argument, to accommodate these changes? For instance, should I change parameterization="se3_log_map" to parameterization="euler_angles" ?

```
def main(
    id_number,
    height=256,
    restart=None,
    model_name="resnet18",
    parameterization="se3_log_map",
    convention=None,
    lr=1e-1,
    batch_size=4,
    n_epochs=400,
    n_batches_per_epoch=100,
):
```
Could you kindly provide guidance on how to resolve the aforementioned issue? I would greatly appreciate your assistance in this matter.

Thank you for your attention to this matter.

Best regards,

**Comment by CYXYZ** [comment]
I've found that when I use parameterizations = ["quaternion"], other errors occur, as follows:

```
(diffpose_copy) (base) cyx@server1:~/autodl-tmp/DiffPose_copy/experiments/deepfluoro$ python register.py
main
ckpt se3_log_map
  0%|                                                                       | 0/111 [00:00<?, ?it/s]convention None
  0%|                                                                       | 0/111 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/data/cyx/autodl-tmp/DiffPose_copy/experiments/deepfluoro/register.py", line 325, in <module>
    main(id_number, parameterization=parameterization)
  File "/home/data/cyx/autodl-tmp/DiffPose_copy/experiments/deepfluoro/register.py", line 290, in main
    df = registration.run(idx)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/autodl-tmp/DiffPose_copy/experiments/deepfluoro/register.py", line 143, in run
    param, geo, tre = self.evaluate(registration)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/autodl-tmp/DiffPose_copy/experiments/deepfluoro/register.py", line 109, in evaluate
    est_pose = registration.get_current_pose()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/diffpose_copy/lib/python3.12/site-packages/diffpose/registration.py", line 248, in get_current_pose
    return convert(self.rotation, 
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/cyx/miniconda3/envs/diffpose_copy/lib/python3.12/site-packages/diffdrr/pose.py", line 148, in convert
    return convert(matrix, parameterization="matrix")
                   ^^^^^^
UnboundLocalError: cannot access local variable 'matrix' where it is not associated with a value

```

**Comment by eigenvivek** [comment]
Hi @CYXYZ sorry for the slow response on this. I am working on a big update to DiffDRR (you can track it [here](https://github.com/eigenvivek/DiffDRR/tree/nifti)), and am waiting to update DiffPose until this is completed. Thank you for your patience.

**Comment by CYXYZ** [comment]
Dear vivek,

I hope this email finds you well. I am writing to inquire about the difference between the image generation methods used in train.py and register.py.

During my review of the code, I noticed that in the train.py process, images are generated using the following line of code: `img = drr(pose, bone_attenuation_multiplier=contrast)`. However, in the register.py file, images are generated using the `Siddon `method.

Could you kindly provide some insights into the distinctions between these two approaches? I am particularly interested in understanding how they differ in terms of image quality, computational efficiency, and any other relevant factors.

Additionally, if there are any specific advantages or disadvantages associated with each method, I would greatly appreciate it if you could elaborate on them.

Thank you very much for your time and assistance. I look forward to hearing from you soon.

Best regards,
cyxyz

**Comment by JDLAmbrose** [comment]
Hi @CYXYZ , I hope everything goes well with you. I met with the same problems as you did. I wonder if you have already solved the questions that you had mentioned? Hoping to get some advice or tricks from you about how you dealing with it. Thanks so much!!!
I'll attach my error below
```ckpt = torch.load(f"work/DiffPose-refactor-se3/experiments/deepfluoro/checkpoints/specimen_{id_number:02d}_best.ckpt")
  0%|                                                                        | 0/24 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/featurize/work/DiffPose-refactor-se3/experiments/deepfluoro/register.py", line 276, in <module>
    main(id_number, parameterization)
  File "/home/featurize/work/DiffPose-refactor-se3/experiments/deepfluoro/register.py", line 196, in main
    df = registration.run(idx) ### PROBLEM IS HERE!!!
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/DiffPose-refactor-se3/experiments/deepfluoro/register.py", line 118, in run
    param, geo, tre = self.evaluate(registration)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/DiffPose-refactor-se3/experiments/deepfluoro/register.py", line 90, in evaluate
    rot = est_pose.get_rotation("euler_angles", "ZYX")
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/diffpose_new/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'RigidTransform' object has no attribute 'get_rotation'
